services:
  frontend:
    build: ./client
    command: npm start
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./server
    command: npm run dev # with nodemon
    volumes:
      - ./server:/index
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=yourpass
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
