name: ESLint

on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint scan and upload results
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint
        run: npm install eslint@8.57.0 --save-dev

      - name: Install SARIF formatter
        run: npm install @microsoft/eslint-formatter-sarif@3.1.0 --save-dev

      - name: Run ESLint with SARIF output
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint ./src \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif

      - name: Upload ESLint SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
