name: Selenium & Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # 1) Drop in any secrets your docker-compose needs
      - name: Create .env file
        run: |
          cat > .env <<EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}    
          EOF


      # 2) Build & start all containers (frontend, backend, db, reverse-proxy)
      - name: Start Docker Compose
        run: docker compose up --build -d

      # 5) Install Google Chrome (for headless Selenium)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub \
            | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 6) Install Python & test deps
      - name: Setup Python & install test requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install selenium>=4.10.0 webdriver-manager>=4.0.0 pytest

      # 7) Run just the registration Selenium test
      - name: Run Selenium registration test
        env:
          BASE_URL: http://localhost
        run: pytest tests/register_test.py -q --maxfail=1 --disable-warnings
