name: Run Unit Tests

on:
  push:
    branches:
      - main
      - is-dev

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "EC2_SQL_USER=${{ secrets.EC2_SQL_USER }}" >> .env
          echo "EC2_SQL_PW=${{ secrets.EC2_SQL_PW }}" >> .env
          echo "EC2_SQL_DB_NAME=${{ secrets.EC2_SQL_DB_NAME }}" >> .env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python test dependencies
        run: |
          pip install selenium webdriver-manager pytest

      - name: Start Docker Compose stack
        run: docker compose up -d --build

      - name: Wait for backend and DB to be ready
        run: sleep 15

      - name: Run Selenium Unit Tests
        run: pytest tests/register_test.py
