name: Frontend Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Install MSW (Mock Service Worker)
        working-directory: client
        run: npm install --save-dev msw

      - name: Install jq for JSON patching
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Patch package.json to transform ESM modules
        working-directory: client
        run: |
          jq '. + {
            jest: {
              transformIgnorePatterns: [
                "node_modules/(?!(axios|msw|@mswjs|@bundled-es-modules)/)"
              ]
            }
          }' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Run Jest unit tests
        working-directory: client
        run: npm test -- --ci --coverage --watchAll=false
